baseURL = "https://pa20bm.github.io/quickstart/"
languageCode = "en-us"
title = "Paul A. Anthony"
theme = "ananke"
publishdir = "docs"

[params]
featured_image = "Users/pennywise/Documents/GitHub/quickstart/images/bookshelf.jpg"
omit_header_text =  true
